export const style = {
  wrapper: {
    marginBottom: "100px",
  },
  recentWork: {
    backgroundColor: "rgba(255, 255, 255, 0)",
    borderRadius: "10px",
    border: "solid 1px #fff",
    fontSize: { lg: "18px", md: "17px", sm: "15px", xs: "18px" },
    padding: {
      lg: "20px 40px",
      md: "18px 36px",
      sm: "16px 34px",
      xs: "20px 40px",
    },
    fontWeight: "500",
    fontStretch: "normal",
    fontStyle: "normal",
    lineHeight: "1.09",
    letterSpacing: "normal",
    textAlign: "left",
    display: "inline-flex",
    color: "#fff",
  },
  title: {
    fontSize: "15px",
    fontWeight: "500",
    fontStretch: "normal",
    fontStyle: "normal",
    lineHeight: "1.31",
    letterSpacing: "1px",
    textAlign: "center",
    color: "#b5b5ba",
    marginBottom: "50px",
  },
  logos: {
    display: "flex",
    textAlign: "center",
    flexWrap: "wrap",
    gap: { md: "60px", sm: "30px", xs: "0" },
    justifyContent: "center",
    flexDirection: { sm: "row", xs: "column" },
  },
};
