export const style = {
  wrapper: {
    maxWidth: "1440px",
    overflow: "hidden",
    margin: "auto",
    backgroundImage: 'url("./packageBg.png"),url("./packageBlur.png")',
    backgroundRepeat: "no-repeat",
    backgroundSize: "contain",
    backgroundColor: "#090a18",
    position: "relative",
  },
  blur: {
    position: "absolute",
    width: { lg: "25rem", xs: "12rem" },
    height: { lg: "12rem", xs: "10rem" },
    top: "0",
    right: "40%",
    background: "rgb(29 120 195 / 38%)",
    filter: "blur(100px)",
    borderRadius: "50%",
  },
  packages: {
    textAlign: "center",
  },
  head: {
    fontSize: { lg: "15px", xs: "13px" },
    fontWeight: "500",
    lineHeight: "1.31",
    color: "#b5b5ba",
    paddingTop: "116px",
  },
  title: {
    fontSize: { lg: "48px", xs: "32px" },
    fontWeight: "500",
    fontStretch: "normal",
    fontStyle: "normal",
    lineHeight: "1",
    letterSpacing: "-0.5px",
    color: "#fff",
    padding: "30px 30px 0 30px  ",
  },
  cards: {
    display: "flex",
    gap: "28px",
    justifyContent: "center",
    padding: {
      lg: "86px 110px 30px 110px",
      md: "86px 60px 30px 60px",
      sm: "86px 30px 30px 30px",
      xs: "86px 18px 30px 18px",
    },
    position: "relative",
    flexDirection: { sm: "row", xs: "column-reverse" },
    flexWrap: "wrap",
    zIndex: "0",
  },
  card: {
    position: "relative",
    flex: "1",
    padding: "34px",
    textAlign: "left",
    backgroundColor: "#171826",

    "&:nth-of-type(3)": {
      height: "fit-content",
    },

    "&:nth-child(1),:nth-child(2)": {
      order: { sm: "0", xs: "1" },
      position: "relative",
      borderRadius: "11px",

      "&::before": {
        content: '""',
        borderRadius: "11px",
        position: "absolute",
        top: "0px",
        left: "0",
        right: { sm: "-16px", xs: "0" },
        bottom: "0px",
        zIndex: "-1",
        backgroundImage:
          "linear-gradient(299deg, rgba(255, 255, 255, 0.1) 60%, rgb(255 255 255) 100%)",
        margin: "-2px",
      },
    },

    "&.card_2:nth-child(2)": {
      order: { sm: "0", xs: "1" },
      position: "relative",
      borderRadius: "11px",
      marginLeft: { sm: "16px", xs: "0" },

      "&::before": {
        content: '""',
        borderRadius: "11px",
        position: "absolute",
        top: "0px",
        left: "0",
        right: "0px",
        bottom: "0px",
        zIndex: "-1",
        backgroundImage:
          "linear-gradient(to top, rgba(56, 183, 255, 0) 57%, #38b7ff 85%), linear-gradient(to bottom, rgba(255, 255, 255, 0.1), rgba(255, 255, 255, 0.1))",
        margin: "-2px",
      },
    },
  },

  badge: {
    backgroundColor: "#38b7ff",
    padding: "8px 13px",
    fontSize: "9px",
    fontWeight: "bold",
    color: "#fff",
    borderRadius: "0 8px",
    position: "absolute",
    top: "-2px",
    right: "-2px",
    letterSpacing: "1px",
  },
  cTitle: {
    fontSize: "24px",
    fontWeight: "500",
    lineHeight: "1.2",
    color: "#fff",
    marginBottom: "12px",
    paddingRight: "24px",
  },
  desc: {
    fontSize: "13px",
    fontWeight: "normal",
    lineHeight: "1.27",
    letterSpacing: "normal",
    color: "rgba(255, 255, 255, 0.7)",
    marginBottom: "33px",
  },
  btn: {
    backgroundColor: "#fff",
    borderRadius: "10px",
    fontSize: { lg: "18px", md: "17px", sm: "15px", xs: "17px" },
    color: "#090a18",
    padding: {
      lg: "20px 0",
      md: "18px 0",
      sm: "16px 0",
      xs: "20px 0",
    },
    fontWeight: "500",
    fontStretch: "normal",
    fontStyle: "normal",
    lineHeight: "1.09",
    letterSpacing: "normal",
    display: "flex",
    justifyContent: "center",
    marginBottom: "28px",
    boxShadow: "inset 0 -4px 0 0 #e8e6e9",
  },
  spots: {
    fontSize: "13px",
    fontWeight: "500",
    lineHeight: "1.27",
    color: "#38b7ff",
    textAlign: "center",
    marginBottom: "33px",
  },
  devider: {
    marginBottom: "33px",
  },
  line: {
    width: "140px",
    height: "1px",
    backgroundColor: "#545454",
  },
  whatGet: {
    fontSize: "13px",
    fontWeight: "500",
    lineHeight: "1.27",
    textAlign: "left",
    color: "#fff",
    marginBottom: "12px",
  },
  list: {
    textAlign: "left",
  },
  item: {
    fontSize: "13px",
    fontWeight: "normal",
    lineHeight: "1.27",
    letterSpacing: "normal",
    color: "#b5b5ba",
    marginBottom: "16px",
    "&:nth-last-child(-n+2)": {
      marginBottom: "34px",
    },
  },
  addOn: {
    borderRadius: "8px",
    backgroundColor: "rgba(255, 255, 255, 0.1)",
    padding: "8px 15px",
    fontSize: "13px",
    fontWeight: "600",
    lineHeight: "1.07",
    letterSpacing: "normal",
    color: "rgba(255, 255, 255, 0.9)",
    width: "fit-content",
    marginBottom: "20px",
  },
  guarantee: {
    fontSize: "13px",
    fontWeight: "normal",
    lineHeight: "1.27",
    letterSpacing: "normal",
    color: "#fff",
    display: "flex",
    alignItems: "center",
    // marginBottom: "50px",
  },

  tags: {
    marginBottom: "38px",
    display: { sm: "flex", xs: "none" },
    gap: "12px",
    flexWrap: "wrap",
  },
  tag: {
    borderRadius: "8px",
    backgroundColor: "rgba(255, 255, 255, 0.1)",
    fontSize: "12px",
    fontWeight: "normal",
    lineHeight: "1.09",
    color: "rgba(255, 255, 255, 0.6)",
    padding: "9px 15px",
    display: "inline-block",
    // marginRight: "12px",
  },
  request: {
    borderRadius: "10px",
    border: "solid 1px #fff",
    backgroundColor: "rgba(255, 255, 255, 0)",
    padding: "20px",
    fontSize: "18px",
    fontWeight: "500",
    lineHeight: "1.09",
    color: "#fff",
    textAlign: "center",
  },

  gradientBorderLeft: {
    position: "relative",
    "&::before": {
      content: '""',
      position: "absolute",
      top: 0,
      left: 0,
      width: "5px", // Adjust thickness as needed
      height: "100%",
      background: "linear-gradient(to bottom, #FF8E53, #FE6B8B)", // Set your desired gradient
      borderRadius: "0 10px 10px 0", // Adjust border radius as needed
      zIndex: 1,
    },
  },
};
