export const style = {
  wrapper: {
    display: "flex",
    justifyContent: "center",
    textAlign: "center",
    marginBottom: "50px",
  },
  hero: {},
  spot: {
    fontSize: "14px",
    borderRadius: "8px",
    border: "solid 1px #38b7ff",
    backgroundColor: "rgba(56, 183, 255, 0.1)",
    padding: "6px 0",
    display: "flex",
    gap: "8px",
    alignItems: "center",
    justifyContent: "center",
    maxWidth: "170px",
    margin: {
      lg: "74px auto 50px auto",
      md: "64px auto 40px auto",
      sm: "50px auto 30px auto",
      xs: "74px auto 50px auto",
    },
    fontWeight: "500",
    lineHeight: "1.06",
    color: "#38b7ff",
  },
  head1: {
    fontSize: { lg: "58px", md: "48px", sm: "40px", xs: "38px" },
    padding: { sm: "0 0 0 6px", xs: "0 24px" },
    // fontWeight: "500",
    // fontStretch: "normal",
    // fontStyle: "normal",
    // lineHeight: "1.12",
    // letterSpacing: "-0.6px",
    // color: "#fff",
    // textAlign: "center",
  },
  head2: {
    fontSize: { lg: "58px", md: "48px", sm: "40px", xs: "38px" },
    padding: { sm: "0", xs: "0 46px" },
    // fontWeight: "500",
    // fontStretch: "normal",
    // fontStyle: "normal",
    // lineHeight: "1.12",
    // letterSpacing: "-0.6px",
    // textAlign: "center",
    color: "rgba(0, 0, 0, 0)",
    "-webkitBackgroundClip": "text",
    backgroundClip: "text",
    "-webkitCextFillColor": "transparent",
    backgroundImage:
      "linear-gradient(to right, #38b7ff, #d782ff 102%), linear-gradient(to bottom, rgba(0, 0, 0, 0), rgba(0, 0, 0, 0))",
    position: "relative",
  },
  client: {
    position: "absolute",
    right: { lg: "-18%", md: "-22%", sm: "-26%" },
    top: { lg: "-4px", md: "-8px", sm: "-12px" },
    transform: { lg: "scale(1)", md: "scale(0.85)", sm: "scale(0.75)" },
    display: { sm: "block", xs: "none" },
  },
  desc: {
    fontSize: { lg: "23px", md: "20px", xs: "18px" },
    fontWeight: "normal",
    fontStretch: "normal",
    fontStyle: "normal",
    lineHeight: "1.35",
    letterSpacing: "normal",
    color: "#b5b5ba",
    marginTop: "30px",
    padding: { sm: "0 0", xs: "0 40px" },
  },
  myDesc: {
    display: { sm: "block", xs: "inline" },
  },
  desc2: {
    position: "relative",
  },
  you: {
    position: "absolute",
    right: "40%",
    top: "-60%",
    transform: { lg: "scale(1)", md: "scale(0.85)", sm: "scale(0.75)" },
    display: { sm: "block", xs: "none" },
  },
};
