export const style = {
  wrapper: {
    backgroundImage: "linear-gradient(to bottom, #fbf7ff, #f5fbff)",
    maxWidth: "1440px",
    overflow: "hidden",
    margin: "auto",
  },
  title: {
    paddingTop: { lg: "120px", md: "100px", sm: "80px", xs: "100px" },
    fontSize: { lg: "44px", sm: "38px", xs: "32px" },
    fontWeight: "500",
    fontStretch: "normal",
    fontStyle: "normal",
    lineHeight: "1",
    textAlign: "center",
    color: "#090a18",
    marginBottom: { lg: "80px", md: "60px", sm: "50px", xs: "74px" },
  },
  cardsContainer: {
    margin: { lg: "0 120px", md: "0 80px", sm: "0 40px" },
    textAlign: "center",
    display: "flex",
    flexDirection: { sm: "row", xs: "column" },
    justifyContent: "space-between",
    gap: { lg: "50px", md: "20px", sm: "0" },
  },
  card1: {},
  icon: {
    marginBottom: "30px",
  },
  cardTitle: {
    fontSize: { lg: "24px", sm: "22px", xs: "24px" },
    fontWeight: "500",
    lineHeight: "1.2",
    letterSpacing: "normal",
    color: "#090a18",
    marginBottom: "18px",
    padding: { sm: "0 22px", xs: "0 32px" },
  },
  desc: {
    fontSize: "16px",
    fontWeight: "normal",
    lineHeight: "1.48",
    letterSpacing: "normal",
    color: "#51535d",
    padding: { sm: "0 16px", xs: "0 26px" },
    marginBottom: "60px",
  },
};
