export const style = {
  wrapper: {
    display: "flex",
    justifyContent: "center",
    flexDirection: { sm: "row", xs: "column" },
  },
  borderRadius: "20px",
  border: "solid 1px rgba(255, 255, 255, 0.2)",
  backgroundColor: "rgba(9, 10, 24, 0.9)",
  display: "flex",
  alignItems: "center",
  fontWeight: "normal",
  fontStretch: "normal",
  fontStyle: "normal",
  lineHeight: "1.11",
  fontSize: { md: "13px", sm: "12px" },
  letterSpacing: "normal",
  color: "rgba(255, 255, 255, 0.7)",
  gap: { md: "2rem", sm: "1rem" },
  marginTop: "30px",
  margin: { sm: "30px 0 0 0", xs: "30px  16px 0 16px" },
  logo: {
    padding: "20px 0 28px 30px",
    margin: "auto",
    "& .MuiAvatar-root ": {
      width: "unset",
      height: "unset",
      borderRadius: "unset",
    },
  },
  "& .hamburger": {
    display: { sm: "none", xs: "block" },
    width: "32px",
    height: "32px",
    position: "absolute",
    right: "2rem",
    border: "1px solid",
    borderRadius: "4px",
    cursor: "pointer",
  },
  navbar: {
    display: { sm: "flex", xs: "none" },
    gap: { md: "30px", sm: "20px" },
    cursor: "pointer",

    "&.mobile_nav": {
      display: { sm: "none", xs: "flex" },
      position: "absolute",
      right: "5vw",
      top: "6rem",
      flexDirection: "column",
      gap: "2rem",
      padding: "3rem",
      backgroundColor: "#171826",
      zIndex: "100",
      cursor: "pointer",
    },
    "&.hide_nav": {
      display: "none",
    },
  },
  bookBtn: {
    display: { sm: "block", xs: "none" },
    borderRadius: "10px",
    border: "solid 1px #767780",
    backgroundColor: " rgba(255, 255, 255, 0.1)",
    padding: { md: "16px 26px", sm: "14px 20px" },
    margin: "10px",
    cursor: "pointer",
    "&:hover": {
      backgroundColor: " rgba(255, 255, 255, 0)",
      border: "solid 1px #63aeff",
      color: "#63aeff",
    },
  },
};
