export const style = {
  wrapper: {
    padding: { lg: "74px 134px", xs: "74px 34px" },
    backgroundColor: "#090a18",
    backgroundImage: 'url("./fBlur.png"),url("./packageBg.png")',
    backgroundRepeat: "no-repeat",
    backgroundSize: "contain",
    maxWidth: "1440px",
    overflow: "hidden",
    margin: "auto",
  },
  footer: {
    display: "flex",
    justifyContent: "space-between",
    flexDirection: { xs: "column", sm: "row" },
    alignItems: { xs: "center", sm: "left" },
    textAlign: { xs: "center", sm: "left" },
  },
  fLeft: {},
  address: {
    fontSize: "13px",
    fontWeight: "normal",
    lineHeight: "1.48",
    letterSpacing: "normal",
    color: "#b5b5ba",
    maxWidth: "200px",
    marginTop: "24px",
  },
  gaurentee: {
    fontSize: "13px",
    fontWeight: "normal",
    lineHeight: "1.48",
    letterSpacing: "normal",
    color: "#fff",
    display: "flex",
    gap: { sm: "12px", xs: "8px" },
    maxWidth: "220px",
    marginTop: "34px",
    flexDirection: { sm: "row", xs: "column" },
  },
  devider: {
    height: "1px",
    width: "140px",
    margin: "74px auto 0",
    backgroundColor: "#464646",
    // marginLeft: { sm: "0", xs: "-40px" },
  },
  copyRight: {
    fontSize: "13px",
    fontWeight: "normal",
    lineHeight: "1.48",
    letterSpacing: "normal",
    color: "#b5b5ba",
  },

  fRight: {
    fontSize: "13px",
    fontWeight: "normal",
    lineHeight: "1.27",
    letterSpacing: "normal",
    color: "#fff",
    display: "flex",
    gap: "64px",
    // paddingRight: { sm: "64px", xs: "0" },
    marginTop: { xs: "30px", sm: "0" },
    "& *": {
      display: "flex",
      flexDirection: "column",
      gap: "14px",
    },
  },
  terms: {
    display: "flex",
    gap: "24px",
    fontSize: "13px",
    fontWeight: "normal",
    lineHeight: "1.27",
    letterSpacing: "normal",
    color: "rgba(255, 255, 255, 0.7)",
  },
  allRights: {
    marginTop: "30px",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    flexDirection: { xs: "column", sm: "row" },
    gap: { xs: "40px", sm: "0" },
  },
};
